services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db_postgres
      - db_oracle

  db_postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: examen_d61_pg
      POSTGRES_USER: user_examen_pg
      POSTGRES_PASSWORD: password_examen_pg
    ports:
      - "5432:5432"

  db_oracle:
    image: gvenzl/oracle-xe:21-slim
    environment:
      ORACLE_PASSWORD: password_examen_oracle
      ORACLE_DATABASE: examen_d61_oracle
    ports:
      - "1521:1521"
